### PR TITLE
fix: update currentSession.user when GoTrueClient.update is called

### LINKED ISSUE #39: currentSession.user is not updated in GoTrueClient.update()
Only `currentUser` is updated in the `GoTrueClient.update()` method. The `currentSession.user` property is not updated. This leads to a discrepancy between these two sources of truth which should always be in sync.

```dart
/// Updates user data, if there is a logged in user.
  Future<GotrueUserResponse> update(UserAttributes attributes) async {
    if (currentSession?.accessToken == null) {
      final error = GotrueError('Not logged in.');
      return GotrueUserResponse(error: error);
    }

    final response =
        await api.updateUser(currentSession!.accessToken, attributes);
    if (response.error != null) return response;

    currentUser = response.user;
    _notifyAllSubscribers(AuthChangeEvent.userUpdated);

    return response;
  }
```

### PR DESCRIPTION
**Pull request by MisterJimson**
Fixes #39
Addresses PR feedback in #40

### CODE REVIEW

**Review by bdlukaa — APPROVED** [review]

**Comment by bdlukaa** [comment]
Could you please add tests?

**Comment by MisterJimson** [comment]
Absolutely. Can you approve my account to run checks so I can test my tests?

Not sure how to run them successfully locally yet. https://github.com/supabase-community/gotrue-dart/issues/47

**Comment by MisterJimson** [comment]
The new stable Dart SDK has new lints that are failing. I can resolve these as well.

**Review by bdlukaa — APPROVED** [review]

**Comment by MisterJimson** [comment]
Hey just wondering if this can be merged and released? 😀

**Pull request merged**
