### PR TITLE
chore: Publish version 0.2.2

### PR DESCRIPTION
**Pull request by DanMossa**
@dshukertjr @bdlukaa

### CODE REVIEW

**Review by dshukertjr — COMMENTED** [review]
Thanks for this PR. Could we also update `version.dart` file?

**Comment by DanMossa** [comment]
@dshukertjr Yes Sorry I keep forgetting about that

**Comment by dshukertjr** [comment]
@DanMossa Sorry, but could we slip [this](https://github.com/supabase-community/gotrue-dart/pull/75) PR in as well. Also, since we only have fixes for this PR, would it make sense to change the version to `0.2.1+1` instead of `0.2.2`?

**Comment by DanMossa** [comment]
Yeah! I'll do that either tonight or tomorrow!

I think it makes sense to do the minor version increase since we're changing a publicly accessable class.

**Comment by dshukertjr** [comment]
I can commit to your branch and merge this one!

>I think it makes sense to do the minor version increase since we're changing a publicly accessable class.

You're right!

**Review by dshukertjr — APPROVED** [review]
LGTM!

**Pull request merged**
