### PR TITLE
Add generateLink method

### PR DESCRIPTION
**Pull request by NiKoTron**
Added generateLink method reffer to the [supabase's Auth(Server only) API
](
https://supabase.com/docs/reference/javascript/auth-api-generatelink#generate-invite-link)

### CODE REVIEW

**Comment by bdlukaa** [comment]
I'm not sure we want to expose server APIs to this client library

**Comment by NiKoTron** [comment]
why not? For example, I use dart as a server language. Also there's api key based restriction to use this method, i guess it should be enough.

**Comment by dshukertjr** [comment]
@bdlukaa I was the one who said let's wait on implementing server side methods on these libraries, because I thought the js library was going to be separated into client side library and server side library on [this issue](https://github.com/supabase/gotrue-js/issues/90), it hasn't been separated and I checked with the team, but it seems like we don't have immediate plans to separate it (still on the road map at some point though). 

With Dart increasing in popularity as a server side language, perhaps we could reconsider it and start adding all the server side methods?

Related https://github.com/supabase-community/gotrue-dart/pull/26

**Comment by dshukertjr** [comment]
@NiKoTron Could we include a test as well for this amazing work that you have done?
https://github.com/supabase/gotrue-js/blob/master/test/GoTrueApi.test.ts#L294

**Comment by NiKoTron** [comment]
@dshukertjr Sorry for the late reply. I made tests similiar to JS impl. also added [dart_jsonwebtoken](https://pub.dev/packages/dart_jsonwebtoken) as a dev_dependency to geneate service jwt.

**Review by dshukertjr — APPROVED** [review]
@NiKoTron Looks amazing! The momentum of server side dart community is amazing!

**Pull request merged**
