### PR TITLE
fix: don't require session after signup

### PR DESCRIPTION
**Pull request by Vinzent03**
fixes https://github.com/supabase-community/supabase-flutter/issues/182
See my [comment](https://github.com/supabase-community/supabase-flutter/issues/182#issuecomment-1212398301) for a question regarding the sign in event and strange naming of  `data`.

### CODE REVIEW

**Review by dshukertjr — COMMENTED** [review]
Thanks for the quick and amazing work here! 

Could we also fix [this test](https://github.com/supabase-community/gotrue-dart/blob/main/test/client_test.dart#L82) to check if session is null but user exists and remove the try/catch? 

I think it's okay to add the property of `GotrueSessionResponse` to `session` from `data` update in this PR as well!

**Comment by Vinzent03** [comment]
I see that `GotrueResponse` has a `rawData` field, which is not set by subclasses. Should I fix that as well or should it be null?

**Comment by dshukertjr** [comment]
@Vinzent03 
I think it's fine to leave it as is, but am also curious how you would go about fixing it! Would it be okay if you show it to me real quick in this PR?

**Review by dshukertjr — APPROVED** [review]
LGTM! Thanks for the amazing work!

**Pull request merged**
